version: "2"
services:
  node:
    image: "node:8"
    container_name: api.preach.dev
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/home/node/app
    ports:
      - "3333:3333"
    command: "yarn dev"
  # db:
  #   image: "mysql:5.7"
  #   container_name: db.preach.dev 
  #   environment:
  #   - MYSQL_ROOT_PASSWORD=root         
  #   ports:
  #     - "5306:3306"
  mongo:
    image: "mongo"
    container_name: mongo.preach.dev     
    ports:
      - "57017:27017"    