version: "2"
services:
  node:
    image: "node:8"
    container_name: api.preach.dev
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=dev
    volumes:
      - ./:/home/node/app
      - ./node_modules:/home/node/app/node_modules
    ports:
      - "3333:3333"
    command: "yarn dev"
